version: "3"
services:
  db:
    image: mysql:8
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root            
      MYSQL_DATABASE: d_base
    ports:
      - "3306:3306"
    volumes:
      - ./data-db:/var/lib/mysql

  backend:
    build: ./backend
    container_name: "backend"
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  redis:
    image: redis
    container_name: "redis"

  frontend:
    build: ./frontend
    container_name: "frontend"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend
volumes:
  data-db: